### ISSUE TITLE
An error AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'? occurs

### ISSUE THREAD

**Issue by Nickup22** [rizkydermawan1992/Face-Detection#3]
Traceback (most recent call last):
  File "C:\Users\nikit\Downloads\Face-Detection-main\Face-Detection-main\facetracking.py", line 17, in <module>
    board = pyfirmata.Arduino(port)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\__init__.py", line 19, in __init__
    super(Arduino, self).__init__(*args, **kwargs)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 101, in __init__
    self.setup_layout(layout)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 157, in setup_layout
    self._set_default_handlers()
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 161, in _set_default_handlers
    self.add_cmd_handler(ANALOG_MESSAGE, self._handle_analog_message)
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 185, in add_cmd_handler
    len_args = len(inspect.getargspec(func)[0])
                   ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

The program is probably designed for the old version of Python

**Comment by TwoTeeToRoomTwo** [comment]
You seem to have a problem with the pyfirmata library related to the new version of Python. In Python 3.0 and later, getargspec has been replaced by getfullargspec

Copy/Paste from Llama-3.1!!! 

Also, are you try running it via:
```
$ torchrun ....
```
